### ISSUE TITLE
Point Just Jazz domains to the new site

### ISSUE THREAD

**Issue by gusaus** [AMTVDigital/justjazz#12]
Here's a list of domains. I'll check off as they are pointed to the new site. 

- [x] [justjazztv.net](http://www.justjazztv.net)
- [x] [justjazzrecords.com](http://justjazzrecords.com)
- [x] [justjazzmagazine.com](http://justjazzmagazine.com)
- [x] [justjazzradio.net](http://justjazzradio.net)
- [x] [justjazzconcertseries.com](http://justjazzconcertseries.com)
- [x] [justjazztvnetwork.com](http://justjazztvnetwork.com)
- [x] [justjazzhistorymuseum.com](http://justjazzhistorymuseum.com)
- [x] [justjazztv.com](http://justjazzhistorymuseum.com)
- [x] [justjazz.org](http://justjazz.org)
- [x] [justjazzliveconcertseries.com](http://justjazzliveconcertseries.com)
- [x] [justjazzmuseum.com](http://justjazzmuseum.com)
- [x] [justjazzcafe.com](http://justjazzcafe.com)

**Comment by gusaus** [comment]
@justjazz Above is the list of Just Jazz domains I found on WIX. Everything but justjazztv.net is pointing to http://www.justjazz.tv/. Say the word and I'll do that one...

...actually, I found justjazzmusic.net but it didn't look like that was connected to WIX. Not sure I can point the domain if it's not.

**Comment by justjazz** [comment]
Go for it. Also, I'm not sure justjazzmusic.net is ours. Check the owner on
that one ;-).
I don't plan on keeping all of these.

Thanks.

Frederick Smith Jr
Founder/CEO
*All Music Television, LLC*
*Just Jazz*
*Just Jazz TV*
*Just Jazz Cafe*
*Just Jazz Records*
*Just Jazz Live Concert Series*
310.365.1865 Cell
310.324.2280 Fax
www.justjazztv.net Web
www.justjazz.tv Web
@All_Music_TV <https://twitter.com/All_Music_TV> Twitter
@JustJazzTV <http://www.instagram.com/justjazztv> IG
JustJazz.TV <http://facebook.com/JustJazz.TV> Facebook

This electronic message, including any attachments, may contain
proprietary, confidential or privileged information for the sole use of the
intended recipient(s). You are hereby notified that any unauthorized
disclosure, copying, distribution, or use of this message is prohibited. If
you have received this message in error, please immediately notify the
sender by reply e-mail and delete it.

**Comment by gusaus** [comment]
ok - all the domains (that you own) are now pointing to https://justjazz.tv/

Probably best to only use https://justjazz.tv/ for all promo and marketing.... give the people one place to goto 😎

**Comment by justjazz** [comment]
Yep. Thanks ;-)

Frederick Smith Jr
Founder/CEO
*All Music Television, LLC*
*Just Jazz*
*Just Jazz TV*
*Just Jazz Cafe*
*Just Jazz Records*
*Just Jazz Live Concert Series*
310.365.1865 Cell
310.324.2280 Fax
www.justjazztv.net Web
www.justjazz.tv Web
@All_Music_TV <https://twitter.com/All_Music_TV> Twitter
@JustJazzTV <http://www.instagram.com/justjazztv> IG
JustJazz.TV <http://facebook.com/JustJazz.TV> Facebook

This electronic message, including any attachments, may contain
proprietary, confidential or privileged information for the sole use of the
intended recipient(s). You are hereby notified that any unauthorized
disclosure, copying, distribution, or use of this message is prohibited. If
you have received this message in error, please immediately notify the
sender by reply e-mail and delete it.
